### PR TITLE
Fix comparison operations for DateTime

### LINKED ISSUE #1126: Comparison with infinity/forever
Some comparisons with infinity give errors:
```
links> var t1 = parseDate("2022-08-04 12:03:12");
t1 = 2022-08-04 12:03:12.000000+1 : DateTime

links> var t2 = forever;
t2 = infinity : DateTime

links> t2 == t1;
***: Runtime error: Comparing infinity with 2022-08-04 12:03:12.000000+1 which either does not make sense or isn't implemented. 

links> t2 <> t1;
***: Runtime error: Comparing infinity with 2022-08-04 12:03:12.000000+1 which either does not make sense or isn't implemented.

links> t2 <= t1;
***: Runtime error: Comparing infinity with 2022-08-04 12:03:12.000000+1 which either does not make sense or isn't implemented. 
```
Other  comparisons are OK:
```
links> t2 >= t1;
true : Bool

links> t1 < t2;
true : Bool

links> t2 < t1;
false : Bool
```

### PR DESCRIPTION
**Pull request by SimonJF**
Equality was not implemented on the server, and comparisons weren't
correctly implemented on the client.

Fixes #1126

### CODE REVIEW

File: lib/js/jslib.js [hunk 1]
```diff
@@ -806,6 +806,14 @@ const _$Links = (function() {
       return true;
     }
 
+    if (_$Types.isDateTime(l) && _$Types.isDateTime(r)) {
```
Comment (dhil) [inline lib/js/jslib.js:809]: I think this code block needs to be moved up before the generic object comparison code. Otherwise I don't think this code will get executed properly.

**Review by dhil — CHANGES_REQUESTED** [review]

File: lib/js/jslib.js (hunk 1 above)
Comment (SimonJF) [reply lib/js/jslib.js:809]: Whoops, good catch.

Comment (SimonJF) [reply lib/js/jslib.js]: (Funnily enough I noticed and fixed this for a few other cases -- this one slipped through the net! I'm grateful for you spotting it.)

**Review by dhil — APPROVED** [review]
