### PR TITLE
Fixed closure conversion to generalize functions over their free type variables when hoisting

### LINKED ISSUE #384: Closure Conversion does not respect free type variables in hoisted functions
I had a look at the current closure conversion code and ran across a problem. Consider the following function

```
sig outer : ((a) {}~> a, [a]) {}~> [a]
fun outer(f, l) {
	fun twice (y){
		f(f(y))
	}
	map(twice,l)
}
```
which evokes that twice has type (a) {}~> a, where a refers to the type variable outer is quantified over (in particular, twice is monomorphic).
Our current implementation of closure conversion will hoist twice to the toplevel, as it should. However, it does not respect free type variables. What *should* happen is that when hoisting the function twice, it is made polymorphic, obtaining some type forall b. (b) {wild}-> b for twice. When calling twice from outer (after hoisting), we would then have to generate a type application that instantiates b as a.

For reference, the current result of closure conversion looks as follows. In particular, twice has type ((8264) {}~> 8264, where 8264 is an unbound type variable.

```
[`Fun (((2069, ((8264) {}~> 8264, "twice", `Global)),
         ([], [(2068, (8264, "", `Local))],
          ([`Let (((2066, (8264, "y", `Local)),
                   ([], `Return (`Variable (2068)))));
             `Let (((2067, (8264, "", `Local)),
                    ([],
                     `Apply ((`Project (("2065", `Variable (2073))),
                              [`Variable (2066)])))))
             ],
           `Apply ((`Project (("2065", `Variable (2073))), [`Variable (2067)])))),
         (Some (2073, ((2065:(8264) {}~> 8264), "env_2069", `Local))),
         `Unknown));
   `Fun (((2072,
           (forall 8280.((8280) {}~> 8280, [8280]) {}~> [8280], "outer",
            `Global)),
          ([8264],
           [(2070, ((8264) {}~> 8264, "", `Local));
             (2071, ([8264], "", `Local))],
           ([`Let (((2064, ([8264], "l", `Local)),
                    ([], `Return (`Variable (2071)))));
              `Let (((2065, ((8264) {}~> 8264, "f", `Local)),
                     ([], `Return (`Variable (2070)))))
              ],
            `Apply ((`TApp ((`TAbs (([8274; 8275; 8276],
                                     `TApp ((`Variable (285),
                                             [8274; { |8275 }; 8276])))),
                             [8264; { |wild }; 8264])),
                     [`Closure ((2069,
                                 `Extend (({2065 => `Variable (2065); }, None))));
                       `Variable (2064)])))),
          None, `Unknown))
   ]
```

### PR DESCRIPTION
**Pull request by frank-emrich**
I've adapted closures.ml such that not only free term variables are collected, but also free type variables occuring in functions. We then generalize the function over those free variables that are actually bound further up in the AST.
To make this type-check, I've changed the `Closure (f, v) constructor in IR values to  `Closure (f, targs, v), now carrying a list of type arguments. This means that `Closure now has a built-in type application. We cannot just enclose TApp (f, targs) in `Closure instead for the following reasons: 
- f is a variable, not a value. It is important to keep it that way, because the function f must be looked up in a map telling us the type of the closure environment it needs. In particular, the value `Variable f would not type-check to prevent using functions without providing the necessary closure environment.
- In order to type-check the closure, we need to know the type arguments that are applied.

I have implemented the necessary changes in the IR type checker. This PR is independent from #392, but I will commit an update to that PR to include the new code closure checking code, but commented out for now. 

This fixes #384

### CODE REVIEW

File: core/closures.ml [hunk 1]
```diff
@@ -407,6 +564,87 @@ struct
           let bs, o = o#bindings bs in
           b :: bs, o
 
+
+      (** Given a list of free variables, return a tuple containing the following:
+        - a list of fresh quantifiers, each corresponding to one free variable
+        - Three maps mapping the old free variables to fresh ones (to be used with Instantiate)  **)
+      method create_substitutions_replacing_free_variables_with_fresh_ones (free_type_vars : Types.quantifier list)  =
```
Comment (jamescheney) [inline core/closures.ml]: This is a very long method name...

File: core/instantiate.ml [hunk 2]
```diff
@@ -297,22 +297,29 @@ let datatype = instantiate_datatype
 
 module SEnv = Env.String
 
-let apply_type : Types.datatype -> Types.type_arg list -> Types.datatype =
-  fun pt tyargs ->
+let type_arguments_to_instantiation_maps : bool -> Types.datatype -> Types.type_arg list -> (datatype * (datatype IntMap.t * row IntMap.t * field_spec IntMap.t)) =
```
Comment (jamescheney) [inline core/instantiate.ml]: Consider putting the types on the next line(s)

File: core/instantiate.ml [hunk 3]
```diff
@@ -297,22 +297,29 @@ let datatype = instantiate_datatype
...
+    if (not arities_okay) then
         (Debug.print (Printf.sprintf "# Type variables (total %d)" (List.length vars));
          let tyvars = String.concat "\n" @@ List.mapi (fun i t -> (string_of_int @@ i+1) ^ ". " ^ Types.show_quantifier t) vars in
          Debug.print tyvars;
          Debug.print (Printf.sprintf "\n# Type arguments (total %d)" (List.length tyargs));
          let tyargs' = String.concat "\n" @@ List.mapi (fun i arg -> (string_of_int @@ i+1) ^ ". " ^ Types.show_type_arg arg) tyargs in
          Debug.print tyargs';
          raise ArityMismatch);
+
+    let vars, remaining_quantifiers = if tyargs_length = vars_length
```
Comment (jamescheney) [inline core/instantiate.ml]: Suggest putting the "if" on the next line

File: core/irTraversals.ml [hunk 4]
```diff
@@ -226,11 +226,21 @@ struct
             let (args, _, o) = o#list (fun o -> o#value) args in
               (* TODO: check arg types match *)
               `ApplyPure (f, args), deconstruct return_type ft, o
-        | `Closure (f, z) ->
+
+        | `Closure (f, tyargs, z) ->
+
             let (f, t, o) = o#var f in
+            let t = if tyargs = []
```
Comment (dhil) [inline core/irTraversals.ml]: Consider using pattern matching rather than if-then-else. I'd probably format the code like this:
```ocaml
let t =
  match tyargs with
  | [] -> t
  | _ ->
     let (remaining_type, instantiation_maps) =
        Instantiate.type_arguments_to_instantiation_maps false t tyargs
     in
     Instantiate.datatype instantiation_maps remaining_type
in
...
```

**Comment by frank-emrich** [comment]
@jamescheney This PR is relatively independent from #392. In particular, they can both be compiled on top of the current master. The only overlap is that this PR changes the type-checking of Closure. I have committed the necessary changes to #392, but commented them out so that everything still compiles independently. This means that we can merge either of those two PRs first and the other one can then easily be adapted.

**Comment by dhil** [comment]
>  The only overlap is that this PR changes the type-checking of Closure. I have committed the necessary changes to #392, but commented them out

Clearly the right thing to do is to merge this first, and then afterwards merge in the type checker. It seems silly to commit a chunk of commented code.

**Comment by jamescheney** [comment]
OK, sounds good to me.

File: core/instantiate.ml [hunk 5]
```diff
@@ -329,7 +339,15 @@ let apply_type : Types.datatype -> Types.type_arg list -> Types.datatype =
                         mapstrcat ", " (fun t -> Types.string_of_type_arg t) tyargs))
         vars tyargs (IntMap.empty, IntMap.empty, IntMap.empty)
     in
-      instantiate_datatype (tenv, renv, penv) t
+    if remaining_quantifiers = [] then
```
Comment (dhil) [inline core/instantiate.ml]: I think it is cleaner to use pattern-matching instead of a bare if-then-else here.

File: core/instantiate.ml [hunk 6]
```diff
@@ -298,22 +298,32 @@ let datatype = instantiate_datatype
...
-    let t, vars =
-      match concrete_type pt with
-        | `ForAll (vars, t) -> t, Types.unbox_quantifiers vars
-        | t -> t, [] in
-    let tenv, renv, penv =
-      if (List.length vars <> List.length tyargs) then
+    let vars, t = TypeUtils.split_quantified_type pt in
+    let tyargs_length = List.length tyargs in
+    let vars_length = List.length vars in
+    let arities_okay = if must_instantiate_all_quantifiers
```
Comment (dhil) [inline core/instantiate.ml]: Put the `if` on a new line. You can format it like
```ocaml
let arities_okay =
  if must_instantiate_all_quantifiers
  then tyargs_length = vars_length
  else tyargs_length <= vars_length
```

File: core/instantiate.ml [hunk 7]
```diff
@@ -298,22 +298,32 @@ let datatype = instantiate_datatype
 
 module SEnv = Env.String
 
-let apply_type : Types.datatype -> Types.type_arg list -> Types.datatype =
-  fun pt tyargs ->
+let type_arguments_to_instantiation_maps :
+      bool -> Types.datatype -> Types.type_arg list -> (datatype * (datatype IntMap.t * row IntMap.t * field_spec IntMap.t)) =
```
Comment (dhil) [inline core/instantiate.ml]: Consider introducing a type alias for `datatype IntMap.t * row IntMap.t * field_spec IntMap.t` to give it an informative name.

File: core/instantiate.ml [hunk 8]
```diff
@@ -298,22 +298,32 @@ let datatype = instantiate_datatype
 
 module SEnv = Env.String
 
-let apply_type : Types.datatype -> Types.type_arg list -> Types.datatype =
-  fun pt tyargs ->
+let type_arguments_to_instantiation_maps :
```
Comment (dhil) [inline core/instantiate.ml]: I suppose the "proper OCaml name" would be `instantiation_maps_of_type_arguments`.

**Comment by jamescheney** [comment]
This looks fairly reasonable now, is it ready?  @dhil are your comments addressed?

**Comment by dhil** [comment]
@jamescheney sure, I am happy. I only made some comments about style.
