### PR TITLE
Desugar modules properly

### LINKED ISSUE #292: Modules and FFI don't go well together.
Minimal example:
```
# a.links
open B
42
```
```
# b.links
alien javascript "/my/js/file.js" {
  foo: () ~> ();
}
```

```
links -m a.links
```
yields
```
*** Error: "Assert_failure refineBindings.ml:265:23"
```

### LINKED ISSUE #456: Typenames can escape their scope
Syntactically, it is possible to declare a typename in any binding context. Therefore it is possible to declare a typename in a local scope, and *that* typename can escape its scope!

Consider the following program.
```links
typename T = Bool;
fun f() {
  typename T = Int;
  0 : T
}

links> f();
0 : T
```
The invocation `f()` produces an integer value, whose type is `T`. But which `T`? Looking at the type constructor environment, it seems that `T = Bool`:
```
links> @tyconenv;
 T = Bool
```
If that is true, then `0 : T` would be ill-typed.

What has happened here, is that the local declaration of `T` within `f` has escaped its scope, and thereby gets conflated with the `T` in the outer scope.

I can think of a couple of potential solutions:

1. Only allow typename declarations in module contexts.
2. Unroll locally defined typenames in positive positions.
3. Disallow locally defined typenames in positive positions.

My preference is for 1, which I believe aligns with other functional programming languages such as `OCaml` and `Haskell`.

### LINKED ISSUE #571: About the semantics of `open`
Automatic resolution and loading of external modules is part of the current Links semantics. For example consider two modules `foo.links` and `bar.links`
```links
# foo.links
var hello = "Hello World";
```
```links
# bar.links
open Foo;

fun main() {
  println(hello)
}
main()
```
Executing `./links -m --path=. bar.links` prints out `Hello World`, that is, the compiler has implicitly loaded the external module `foo.links` for us.

However, if you were to slightly rewrite `bar.links` to
```links
# bar.links
fun main() {
  println(Foo.hello)
}
main()
```
then executing `./links -m --path=. bar.links` yields a compile time error
```
bar.links:2: Type error: Unknown variable Foo.hello.
```
Thus the compiler did not load `foo.links` for us, which may be a little surprising if we think of ML languages. However, it is arguably OK, because a simple typo could potentially cause the compiler to load an arbitrary amount of modules.

We can instruct the compiler to load `foo.links` for us by adding back the `open`
```links
open Foo;

# bar.links
fun main() {
  println(Foo.hello)
}
main()
```
Note that `hello` is still prefixed by `Foo`. Running `./links -m --path=. bar.links` prints out `Hello World` just as the first program did. So `open` really acts as an "import statement" instructing the compiler to go figure out how to load the said module.

Now, we also have support for local module definitions. In particular, local definitions may shadow external file-based modules.
```links
open Foo;

module Foo {
  var hello = "Hello from Bar!";
}

open Foo;

fun main() {
  println(hello)
}
main()
```
Running `./links -m --path=. bar.links` prints `Hello from Bar!`. The `bar.links` program contains two `open Foo` expressions. The two are morally different. The first instance **imports a global module**, whilst the second instance **opens a local module** (or more generally, opens a module that has already been loaded [local modules are trivially loaded]).

An import entails resolving a module on disk and transitively load its dependencies, which is quite convenient, but as I argue it is different from simply "opening" a module to bring its contents into scope.

I would like the difference to be reflected in the language for two reasons

* It can lead to mildly confusing behaviour.
* The implementation of the loader can be vastly simplified, as currently the loader needs to understand the binding structure and semantics.

I propose to add `import` (or `using`) as a primitive, whose intended semantics is to load global modules, e.g.
```links
# bar.links
import Foo;

fun main() {
  println(hello)
}
main()
```
where the `import` instructs the compiler to locate `foo.links` on the disk, such that running `./links -m --path=. bar.links` prints `Hello World`. Moreover, omitting the `import` or using `open` instead would be a compile time error, e.g.
```links
# bar.links
open Foo;

fun main() {
  println(hello)
}
main()
```
running `./links -m --path=. bar.links` should yield `error: unbound module Foo`, because no such module `Foo` has been loaded.

Having a primitive like `import` enables the programmer to clearly express their intent, and it provides an easy way to compute the dependency graph of a given module without having to have knowledge of the Links binding structure and semantics.

Further down the pipeline, I can also envisage using `import` to import/use whole namespaces rather than a single module. But I will leave that for future consideration.

### LINKED ISSUE #595: How to print type names from opened modules?
Consider the following program:

```
module A {
  typename Foo = Int;
}

open A;
sig x : Foo
var x = 3;
x
```

We currently have a test case assuming that the result of this program should be printed as `3 : A.Foo`, meaning that we fully expand the name to its original location. That sounds reasonable, but doing so systematically would mean that printing all types from the prelude would be prefixed similarly. I would prefer seeing `Maybe` as a type name rather than `Prelude.Maybe`. Note that this only affects the printing of types, not the types that the user writes (as seen in the example program, we can write `Foo` after opening `A`. Similarly, the prelude is implicitly opened in each program).

Here are a few solutions:
1. Do not expand the type names, meaning that the result of the program above would be   `3 : Foo` instead of  `3 : A.Foo`.
2. Expand all type names, meaing that we would see  `3 : A.Foo`, but also `Prelude.Mayne`.
3. Expand user-written type names (e.g., do  `3 : A.Foo`) but allow some minor inconsistency by suppressing `Lib` and `Prelude` when printing the type names from those modules.

### LINKED ISSUE #598: Boundary Peek
Modules break the lexical scope as exemplified by the following program
```links
# scope.links
module A {
  var x = "A1";
}

open A;

module A {
  var x = "A2";
}

println(x)
```
The first module `A` is opened, and hence `x` is brought into scope unqualified. The second definition of `A` shadows the first, but crucially its contents are not brought into the toplevel scope, hence the program should print `A1`, but running `./links -m scope.links` produces the output
```
A2
() : ()
```
Thus it is possible to peek across scope boundaries.

The problem has little to do with modules, it just happens that modules expose the problem. The real problem is that our handling of names in the front end is broken. We should really be resolving names early on in the front end to rule out a whole class of problems.

### PR DESCRIPTION
**Pull request by dhil**
This patch fixes all known scoping issues due to modules (except #596
which is related to the loader/chaser). It makes no changes to the
implementation strategy of the current module system, rather, it fixes
the current implementation such that it is hygienic.

It fixes some bugs due to misconceptions such as qualifying labels in
variants. Labels should never be qualified as they are structural.

Amongst other minor improvements are better error handling and
printing of error messages.

My intention is to use the current module system as "an executable
specification" for the new, proper module system.

#### Meta
Depends on PR #599.
Contributes toward resolving #337 and #603.
Resolves #292, resolves #456, resolves #571, resolves #595, and resolves #598.

### CODE REVIEW

File: core/desugarModules.ml [hunk 1]
```diff
@@ -17,328 +24,497 @@
...
+       type checker. We produce a "best guess" of its name, which is
+       simply its qualified form. *)
+    let best_guess : name list -> name
+      = String.concat "."
+
+    let module' : name list -> t -> scope
+      = fun names scopes ->
+      try S.Resolve.module' names scopes.inner
+      with Notfound.NotFound _ ->
+        S.Resolve.module' names scopes.outer (* Allow any errors propagate. *)
```
Comment (SimonJF) [inline core/desugarModules.ml]: minor: "allow any errors _to_ propagate"

File: core/desugarModules.ml [hunk 2]
```diff
@@ -17,328 +24,497 @@
...
+
+let rec desugar_module : ?toplevel:bool -> Epithet.t -> Scope.t -> Sugartypes.binding -> binding list * Scope.t
+  = fun ?(toplevel=false) renamer scope binding ->
+  match binding.node with
+  | Module (name, bs) ->
+     let visitor = desugar ~toplevel (Epithet.remember ~escapes:(not toplevel) name renamer) (Scope.renew scope) in
+     let bs'    = visitor#bindings bs in
+     let scope' = visitor#get_scope in
+     let scope'' = Scope.Extend.module' name scope' scope in
+     (* Printf.printf "enter_module before:\n%s\n%!" (string_of_scopes scope);
```
Comment (SimonJF) [inline core/desugarModules.ml]: Can these comments go before merging?
(Same for the other comments below; maybe a better way of doing this would be to have debug log levels...)

File: core/desugarModules.ml [hunk 3]
```diff
@@ -17,328 +24,497 @@
...
+      * Printf.printf "enter_module after:\n%s\n%!" (string_of_scopes scope''); *)
+     (bs', scope'')
+  | _ -> assert false
+and desugar ?(toplevel=false) (renamer : Epithet.t) (scope : Scope.t) =
+  let open Sugartypes in
+  object(self : 'self_type)
+    inherit SugarTraversals.map as super
+
+    val scope : Scope.t ref = ref scope
```
Comment (SimonJF) [inline core/desugarModules.ml]: Why not use `mutable val` here, instead of a combination of vals and references?

File: core/desugarModules.ml [hunk 4]
```diff
@@ -17,328 +24,497 @@
...
+                    ~pos ~stage:Errors.DesugarModules
+                    ~message:("Modules are not enabled. To enable modules set the `modules' setting to true or use the flag `-m'."))
 
-    method! unary_op = function
-      | UnaryOp.Name n -> (self, UnaryOp.Name (resolve n term_shadow_table))
-      | uo -> super#unary_op uo
+    method bindings = function
+      | [] -> []
+      | { node = Import names; pos } :: bs ->
+         self#extension_guard pos;
```
Comment (SimonJF) [inline core/desugarModules.ml]: This is _very_ pretty.

File: core/desugarModules.ml [hunk 5]
```diff
@@ -17,328 +24,497 @@
  *
  *  --->
  *
- * val Foo.bobsleigh = ...;
- * fun Foo.x() { ...}
- * fun Foo.Bar.y() { ... }
- * val x = ...;
+ * val Foo0.bobsleigh0 = ...;
```
Comment (SimonJF) [inline core/desugarModules.ml]: I'm assuming these are internal and aren't exposed like this -- could you modify the comment to make this clearer?

File: core/desugarModules.ml (hunk 3 above)
Comment (dhil) [reply core/desugarModules.ml]: Good point.

File: core/desugarModules.ml (hunk 5 above)
Comment (dhil) [reply core/desugarModules.ml]: Sure!

File: core/desugarModules.ml (hunk 2 above)
Comment (dhil) [reply core/desugarModules.ml]: Oh yes, I will delete them. Thanks!

File: core/desugarModules.ml (hunk 1 above)
Comment (dhil) [reply core/desugarModules.ml]: Cheers!

**Comment by dhil** [comment]
@SimonJF I think this is ready now.

A few other highlights:

- Modules work in the REPL.
- Slightly improves the debugging experience of generated JavaScript as the translation of qualified names adds less noise.

**Comment by SimonJF** [comment]
As we discussed earlier, I can't get this to run. I think this is something on my end, but I'm baffled as to what, since I've done a clean checkout, am on the right branch, have done `make clean && make nc && dune install`, and I've even used your config file: 

```
[simon@dazzle daniel-links]$ ./links --config=/home/simon/scraps/daniel-config --path=examples/webserver:examples/games:examples/dictionary:examples examples/webserver/examples.links 
examples/webserver/examples.links:35: Type error: The function
    `addRoute'
has type
    `(String, (String) {hear{a}}~> Page) ~c~> ()'
while the arguments passed to it have types
    `String'
and
    `(String) {|wild|hear{a}}~> ()'
and the currently allowed effects are
    `|wild|d'
In expression: addRoute("/examples/draggable.links", fun(_) {Draggable.main()}).
```

Is this just me? Could someone else try?

**Comment by frank-emrich** [comment]
I can reproduce Simon's problem using a default configuration, besides enabling modules with `-m`.

**Comment by dhil** [comment]
That is strange. I cannot reproduce the problem on either of my machine with the default configuration with modules enables or my personal configuration. Both the `examples.links` and `examples-nodb.links` run as expected.

**Comment by dhil** [comment]
@SimonJF @frank-emrich try: `./links -m --path=examples:examples/webserver:examples/games:examples/dictionary examples/webserver/examples.links`

Note that `examples` have moved to the front of the list. I think the problem you are experiencing is a problem with loader. There are multiple candidates for `draggable.links`, but the current loader/chaser does not warn you in case of an ambiguous choice (the new loader does).
