### PR TITLE
Nicer IR type-checking error reporting

### LINKED ISSUE #539: Broken error message when fail_on_ir_type_error is enabled
Something is horribly broken with errors generated when `fail_on_ir_type_error` is enabled:

```
*** Fatal error : Unknown exception during IR type-checking: (Failure
   "IR Type Error: Type mismatch:\
  \n Expected:\
  \n`Application (({ Types.Abstype.id = \"List\"; name = \"List\";\
  \n                 arity =\
  \n                 [(CommonTypes.PrimaryKind.Type,\
  \n                   (CommonTypes.Linearity.Unl, CommonTypes.Restriction.Any))]\
  \n                 },\
  \n               [`Type (`MetaTypeVar (Point @ 0x7f1861672d80 `Var ((397,\
  \n                                                                   (CommonTypes.Linearity.Unl,\
  \n                                                                    CommonTypes.Restriction.Any),\
  \n                                                                   `Rigid))))\
  \n                 ]))\
  \n Actual:\
  \n `ForAll ((ref ([]),\
  \n          `Application (({ Types.Abstype.id = \"List\"; name = \"List\";\
  \n                           arity =\
  \n                           [(CommonTypes.PrimaryKind.Type,\
  \n                             (CommonTypes.Linearity.Unl,\
  \n                              CommonTypes.Restriction.Any))\
  \n                             ]\
  \n                           },\
  \n                         [`Type (`MetaTypeVar (Point @ 0x7f1861673788 `Var (\
  \n                                               (378,\
  \n                                                (CommonTypes.Linearity.Unl,\
  \n                                                 CommonTypes.Restriction.Any),\
  \n                                                `Rigid))))\
  \n                           ]))))\
```
`fail_on_ir_type_error` is at the moment a hard-coded setting in `irCheck.ml`.

### PR DESCRIPTION
**Pull request by frank-emrich**
This is just a cleanup of the error handling in the IR type-checker. In particular, there should be a nicer separation between error handling done inside of the type-checker and the handling done outside of it.

Most of the changes are just because I got rid of some polymorphic variants.

Fixes #539 (together with  3062b583627b3ba750bed5e426593ab33b43ecff).

### CODE REVIEW

**Comment by jamescheney** [comment]
#301 is a pull request, are you sure it's not some other issue this fixes?

**Comment by frank-emrich** [comment]
Oops, you're right. Edited the description.

**Comment by dhil** [comment]
I think, in the future we should define IR errors in a separate module from the front end errors.

File: core/irCheck.ml [hunk 1]
```diff
@@ -5,30 +5,85 @@ open Ir
...
+  | STC    of tail_computation
+  | SVal   of value
+  | SSpec  of special
+  | SBind  of binding
+  | SBinds of binding list
+  | SProg  of program
+  | SNone
+
+let string_of_occurrence : ir_snippet -> string = function
+  | STC tc -> "\noccurring in IR tail computation:\n" ^ Ir.string_of_tail_computation tc
```
Comment (jstolarek) [inline core/irCheck.ml]: I don't like inserting `\n` into strings. Is there no function or combinator suited to do just that?

Also, maybe align `->`?

File: core/irCheck.ml [hunk 2]
```diff
@@ -5,30 +5,85 @@ open Ir
...
+  | SVal v -> "\noccurring in IR value:\n" ^ Ir.string_of_value v
+  | SSpec s -> "\noccurring in IR special tail computation:\n" ^ Ir.string_of_special s
```
Comment (jstolarek) [inline core/irCheck.ml]: Doesn't fit 80 columns.

File: core/irCheck.ml [hunk 3]
```diff
@@ -1050,6 +1116,12 @@ struct
                       Some defs, o
             in
               Module (name, defs), o
+      in
+      fun b -> translate_helper_exns binding_inner b (SBind b)
+
```
Comment (jstolarek) [inline core/irCheck.ml]: Why so many empty lines?

File: core/irCheck.ml [hunk 4]
```diff
@@ -990,7 +1053,9 @@ struct
                 let o = OptionUtils.opt_app o#remove_binder o z in
                 let o = List.fold_right (fun b o -> o#remove_binder b) xs o in
                 f, tyvars, xs, body, z, location, o
-              with e -> handle_ir_type_error e (f, tyvars, xs, body, z, location, o) in
+              ) in
+              let f, tyvars, xs, body, z, location, o =
+               handle_ir_type_error lazy_check (f, tyvars, xs, body, z, location, o) (SBind binding) in
```
Comment (jstolarek) [inline core/irCheck.ml]: Does not fit 80 columns.

File: core/irCheck.ml [hunk 5]
```diff
@@ -881,6 +938,11 @@ struct
         | LensJoin _
         | LensPut _ -> (* just do type reconstruction *) super#special special
 
+      in
+      fun special -> translate_helper_exns special_inner special (SSpec special)
+
```
Comment (jstolarek) [inline core/irCheck.ml]: Why so many empty lines?

File: core/irCheck.ml [hunk 6]
```diff
@@ -618,36 +669,42 @@ struct
...
             let right, rt, o = o#computation right in
-            o#check_eq_types vt (`Primitive Primitive.Bool) (`TC orig);
-            o#check_eq_types lt rt (`TC orig);
+            o#check_eq_types vt (`Primitive Primitive.Bool) (STC orig);
+            o#check_eq_types lt rt (STC orig);
             If (v, left, right), lt, o
 
+      in
+      fun tc -> translate_helper_exns tail_computation_inner tc (STC tc)
+
```
Comment (jstolarek) [inline core/irCheck.ml]: Why so many empty lines?

File: core/irCheck.ml [hunk 7]
```diff
@@ -547,14 +593,19 @@ struct
...
-              ensure (eq_types (`Value orig) (o#extract_type_equality_context ()) (vt, t) || is_sub_type (vt, t)) (Printf.sprintf "coercion error: %s is not a subtype of %s"
-                                         (string_of_datatype vt) (string_of_datatype t)) (`Value orig);
+              ensure (eq_types (SVal orig) (o#extract_type_equality_context ()) (vt, t) || is_sub_type (vt, t)) (Printf.sprintf "coercion error: %s is not a subtype of %s"
+                                         (string_of_datatype vt) (string_of_datatype t)) (SVal orig);
               Coerce (v, t), t, o
               end
 
+      in
+      fun value -> translate_helper_exns value_inner value (SVal value)
+
```
Comment (jstolarek) [inline core/irCheck.ml]: Why so many empty lines?

File: core/irCheck.ml [hunk 8]
```diff
@@ -547,14 +593,19 @@ struct
               end
             else
               begin
-              ensure (eq_types (`Value orig) (o#extract_type_equality_context ()) (vt, t) || is_sub_type (vt, t)) (Printf.sprintf "coercion error: %s is not a subtype of %s"
-                                         (string_of_datatype vt) (string_of_datatype t)) (`Value orig);
+              ensure (eq_types (SVal orig) (o#extract_type_equality_context ()) (vt, t) || is_sub_type (vt, t)) (Printf.sprintf "coercion error: %s is not a subtype of %s"
+                                         (string_of_datatype vt) (string_of_datatype t)) (SVal orig);
               Coerce (v, t), t, o
               end
```
Comment (jstolarek) [inline core/irCheck.ml]: Why an empty line here?

File: core/irCheck.ml [hunk 9]
```diff
@@ -5,30 +5,85 @@ open Ir
...
+    f x
+  with
+    | TypeUtils.TypeDestructionError msg ->
+      raise_ir_type_error msg occurrence
+    | Instantiate.ArityMismatch (takes, given) ->
+      let msg =
+        Printf.sprintf "Arity mismatch during type application/instantiation. \
+                        Providing %d type arguments to function that takes %d." given takes in
+      raise_ir_type_error msg occurrence
+
```
Comment (jstolarek) [inline core/irCheck.ml]: Why so many empty lines?

File: core/irCheck.ml [hunk 10]
```diff
@@ -5,30 +5,85 @@ open Ir
...
+           "\n-------------------------------------------------------------------\n" );
+        alternative
+      | exn ->
+        let msg =
+          "Encountered exception during IR type-checking, saying:\n" ^
+          Printexc.to_string exn in
+        let occurrence_string = string_of_occurrence occurrence in
+        Debug.print (msg ^ occurrence_string);
+        alternative
+
```
Comment (jstolarek) [inline core/irCheck.ml]: Why so many empty lines?

File: core/irCheck.ml [hunk 11]
```diff
@@ -5,30 +5,85 @@ open Ir
...
-let handle_ir_type_error error alternative =
-  match error with
-    | IRTypeError msg
-    | TypeUtils.TypeDestructionError msg ->
-      if fail_on_ir_type_error then
-        failwith ("IR Type Error: " ^ msg)
-      else
+  let occurrence_string = string_of_occurrence occurrence in
+  raise (Errors.IRTypeError (msg ^ occurrence_string))
+
```
Comment (jstolarek) [inline core/irCheck.ml]: Why so many empty lines?

File: core/irCheck.ml [hunk 12]
```diff
@@ -5,30 +5,85 @@ open Ir
...
+           Print the error and return the alternative value *)
         Debug.print
           ("\n--------------------------------------------------------------------\n" ^
-            "Continuing after IR Type Error: " ^
-            msg ^
-            "\n-------------------------------------------------------------------\n" ); alternative
-    |  e-> failwith ("Unknown exception during IR type-checking: " ^ Printexc.to_string e)
+           "Continuing after IR Type Error:\n" ^
+           msg ^
+           "\n-------------------------------------------------------------------\n" );
```
Comment (jstolarek) [inline core/irCheck.ml]: Why separate arguments to a function with empty lines?

**Comment by jstolarek** [comment]
Hm... I just made some comments about too many empty lines, but now it looks like a github glitch. Let me check out your branch and see what it actually looks like. I'll update my comments in a few minutes.

**Comment by jstolarek** [comment]
Ok, comments updated. Most were not a glitch.

File: core/typeUtils.ml [hunk 13]
```diff
@@ -54,7 +54,7 @@ let extract_row t = match concrete_type t with
   | `Record row -> row
   | `Variant row -> row
   | t ->
-      failwith
+      error
```
[the remark this answers is not in the document]
Comment (frank-emrich) [reply core/typeUtils.ml]: `error` is defined in `typeUtils` as a function creating `TypeDetructionError` exceptions

File: core/irCheck.ml (hunk 9 above)
Comment (frank-emrich) [reply core/irCheck.ml]: Indeed, here it doesn't make much sense, removed them

File: core/irCheck.ml (hunk 7 above)
Comment (frank-emrich) [reply core/irCheck.ml]: Many of the larger methods in `irCheck` now start with a big nested function, which is used at the end. I tried to make that visually more obvious, but I guess it's a matter of taste.

File: core/irCheck.ml (hunk 6 above)
Comment (frank-emrich) [reply core/irCheck.ml]: Intentional, see other comment

File: core/irCheck.ml (hunk 3 above)
Comment (frank-emrich) [reply core/irCheck.ml]: Intentional, see other comment

File: core/irCheck.ml (hunk 8 above)
Comment (frank-emrich) [reply core/irCheck.ml]: Trying to separate the inner function visually from the other one

File: core/irCheck.ml (hunk 1 above)
Comment (frank-emrich) [reply core/irCheck.ml]: Yes, I agree it's ugly. We have a little pretty-printier in `pp.ml`, I'll give it a try.

File: core/irCheck.ml (hunk 2 above)
Comment (frank-emrich) [reply core/irCheck.ml]: Did we ever decide on using a 80 column limit? I agree that many lines in `irCheck` are too long, but I really hope we're not going for a 80 column limit.

File: core/irCheck.ml (hunk 7 above)
Comment (jstolarek) [reply core/irCheck.ml]: Hm... I don't feel having 4-5 empty lines looks good or helpful. Wonder what others think.

File: core/irCheck.ml (hunk 2 above)
Comment (jstolarek) [reply core/irCheck.ml]: No, we never did, so feel free to ignore :-) I personally don't go beyond 80th column.

File: core/irCheck.ml (hunk 7 above)
Comment (frank-emrich) [reply core/irCheck.ml]: I just tend to keep scrolling past the end of very long functions/methods when the next one starts immediately afterwards. But I'm happy to remove those extra lines.

**Comment by frank-emrich** [comment]
I removed the extra empty lines now

File: core/irCheck.ml (hunk 1 above)
Comment (frank-emrich) [reply core/irCheck.ml]: How do you like the following:


```
let string_of_occurrence : ir_snippet -> string =
  let nl = "\n" in
  function
  | STC tc    ->
     nl ^
     "occurring in IR tail computation:" ^
     nl ^
     Ir.string_of_tail_computation tc
  | ...
```


I didn't use the `pp` thing, it turned out to make things more complicated, rather than less.

**Comment by frank-emrich** [comment]
@dhil 
> I think, in the future we should define IR errors in a separate module from the front end errors.

The only issue here is that the current design is such that `driver.ml` wraps all of the actual processing with the error handling done in `errors.ml`. This is good, because it prevents unhandled errors to escape. On the other hand, it means that there is one location where all the error handling happens.

This is why as part of this PR, I had to do the opposite: moving `IRTypeError` from `irCheck.ml` to `errors.ml`.

**Comment by dhil** [comment]
> @dhil
> 
> > I think, in the future we should define IR errors in a separate module from the front end errors.
> 
> The only issue here is that the current design is such that `driver.ml` wraps all of the actual processing with the error handling done in `errors.ml`. This is good, because it prevents unhandled errors to escape. On the other hand, it means that there is one location where all the error handling happens.
> 
> This is why as part of this PR, I had to do the opposite: moving `IRTypeError` from `irCheck.ml` to `errors.ml`.

Yes I understand. I think, again for the future, we should have a "driver" for the front end and another for the back end. Then we would have a third module that composes them.

**Comment by jamescheney** [comment]
@jstolarek @dhil are your concerns addressed?  I think we should merge this and create other issue(s) about reorganizing the errors to separate frontend and backend error handling (which might happen naturally relatedly to #547).
