### PR TITLE
Fix #706.

### LINKED ISSUE #706: ***: Error: Links_core.Utility.Disk.AccessError("") when using DB driver from OPAM install on 0.9
Using the installed version of Links (try pinning it) will result in the above error. I have observed this error on Wilmer's and Sid's machines, necessitating source installations. I have also reproduced it on a fresh VM.

This is something to do with the interplay between OPAM and the dynamic linking code, and is of course a blocker for 0.9.

### PR DESCRIPTION
**Pull request by SimonJF**
The issue was with an edge case which was the result of an empty
database drivers setting string.

This patch ensures that an AccessError is correctly handled when looking
up database drivers. It also special-cases the (common) case of an empty
string.

### CODE REVIEW

File: core/databaseDriver.ml [hunk 1]
```diff
@@ -79,7 +79,10 @@ module Locator = struct
          loop false pattern (opam_share driver_name)
       | [] -> raise Not_found
       | path :: paths ->
-         match Glob.files path pattern with
+         let files =
```
Comment (dhil) [inline core/databaseDriver.ml]: Since 4.08 we can use exception patterns in a nested match, so
```ocaml
match Glob.files path pattern with
| [] -> loop fallback pattern paths
| fs -> fs
| exception Disk.AccessError _ -> []
```
